import { Theme } from "Theme/Theme.slint";
import { Sidebar } from "components/Sidebar.slint";
import { PluginsPage } from "pages/plugins.slint";
import { ConvertPage } from "pages/convert.slint";

export component MainWindow inherits Window {
    width: 1000px;
    height: 650px;
    background: Theme.bg;
    title: "Meltforge";
    property <int> current_page: 0;
    HorizontalLayout {
        Sidebar {
            current: root.current_page;
            select(i) => {
                root.current_page = i;
            }
        }

        if root.current_page == 0: ConvertPage { }
        if root.current_page == 1: PluginsPage { }
    }
}
