[workspace]
members = [ "mf-cli",
    "mf-core",
]
resolver = "2"

[workspace.package]
edition = "2021"
workspace.resolver = "3"

[workspace.dependencies]
clap = "4.5.47"
image = "0.25.8"
thiserror = "2.0.17"
