import { Theme } from "../Theme/Theme.slint";
import { ButtonPrimary } from "../components/buttonprimary.slint";
import { FileItemList } from "../components/fileitemlist.slint";

export component ConvertPage inherits Rectangle {
    callback add_file_clicked();
    callback convert_clicked();
    in-out property <[string]> files: [];
    background: Theme.surface;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    padding-left: 16px;
    padding-right: 16px;
    padding-top: 8px;
    VerticalLayout {
        Rectangle {
            padding-left: 16px;
            padding-right: 16px;
            padding-top: 8px;
            background: Theme.surface;
            horizontal-stretch: 1;
            vertical-stretch: 1;
            FileItemList {
                files: files;
            }
        }

        Rectangle {
            background: Theme.bg_light;
            horizontal-stretch: 1;
            height: 48px;
            VerticalLayout {
                Rectangle {
                    vertical-stretch: 1;
                }

                HorizontalLayout {
                    ButtonPrimary {
                        label: "Add File";
                        clicked => {
                            root.add_file_clicked()
                        }
                    }

                    padding-left: 20px;
                    Rectangle {
                        horizontal-stretch: 1;
                    }

                    ButtonPrimary {
                        label: "convert";
                        clicked => {
                            root.convert_clicked()
                        }
                    }

                    padding-right: 20px;
                }

                Rectangle {
                    vertical-stretch: 1;
                }
            }
        }
    }
}
