import { Theme } from "../Theme/Theme.slint";
import { Button } from "../components/button.slint";

export component PluginsPage inherits Rectangle {
    background: Theme.surface;
    min-width: 960px;
    min-height: 600px;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    padding-left: 16px;
    padding-right: 16px;
    padding-top: 8px;
    VerticalLayout {
        Rectangle {
            padding-left: 16px;
            padding-right: 16px;
            padding-top: 8px;
            background: Theme.surface;
            horizontal-stretch: 1;
            vertical-stretch: 1;
        }
    }
}
